local manager = require('main.scripts.manager')

function init(self)
	msg.post("@render:", "clear_color", { color = vmath.vector4(12 / 255, 241 / 255, 1, 0) })
	msg.post(".", "acquire_input_focus")

	manager.init()
end

function update(self, dt)
	manager.update(dt)
end

function on_message(self, message_id, message, sender)
	if message_id == hash('reboot') then
		manager.reboot()
	end
end

function on_input(self, action_id, action)
	manager.input(action_id, action)
end
